import { demo } from './challenge_01.js'
import {} from './challenge_02.js'
import {} from './challenge_03.js'
import {} from './challenge_04.js'
import {} from './challenge_05.js'
import {} from './challenge_06.js'
import {} from './challenge_07.js'
import {} from './challenge_08.js'
import {} from './challenge_09.js'
import {} from './challenge_10.js'
import {} from './challenge_11.js'
import {} from './challenge_12.js'
import {} from './challenge_13.js'
import {} from './challenge_14.js'
import {} from './challenge_15.js'
import {} from './challenge_16.js'
import {} from './challenge_17.js'
import {} from './challenge_18.js'
import {} from './challenge_19.js'
import {} from './challenge_20.js'
import {} from './challenge_21.js'
import {} from './challenge_22.js'
import {} from './challenge_23.js'
import {} from './challenge_24.js'


demo()